// [branch, city, postcode, country]
export const ASDA_FINAL_BRANCH_ROWS = Object.freeze([
  Object.freeze(["Enfield Supercentre","Enfield","EN1 3DG","England"]),
  Object.freeze(["Wembley Supercentre","Wembley","HA9 0JU","England"]),
  Object.freeze(["Colindale Supercentre","Colindale","NW9 0AS","England"]),
  Object.freeze(["Crossharbour Supercentre","Crossharbour","E14 9OD","England"]),
  Object.freeze(["Beckton Supercentre","Beckton","E6 6LG","England"]),
  Object.freeze(["Clapham Junction","Clapham","SW11 1TB","England"]),
  Object.freeze(["Watford Supercentre","Watford","WD24 7UA","England"]),
  Object.freeze(["Milton Keynes Supercentre","Milton","MK1 1QB","England"]),
  Object.freeze(["Slough Supercentre","Slough","SL1 9LA","England"]),
  Object.freeze(["Swindon Supercentre","Swindon","SN25 4BG","England"]),
  Object.freeze(["Bristol Whitchurch","Bristol","BS14 0ST","England"]),
  Object.freeze(["Bristol Patchway Supercentre","Bristol","BS34 5TL","England"]),
  Object.freeze(["Bournemouth Supercentre","Bournemouth","BH8 8DL","England"]),
  Object.freeze(["Poole Supercentre","Poole","BH15 1DF","England"]),
  Object.freeze(["Southampton Supercentre","Southampton","SO14 0FL","England"]),
  Object.freeze(["Cardiff Supercentre","Cardiff","CF11 8AZ","Wales"]),
  Object.freeze(["Swansea Supercentre","Swansea","SA1 7DF","Wales"]),
  Object.freeze(["Newport Supercentre","Newport","NP20 2NY","Wales"]),
  Object.freeze(["Plymouth Supercentre","Plymouth","PL6 8BF","England"]),
  Object.freeze(["Exeter Supercentre","Exeter","EX4 4AL","England"]),
  Object.freeze(["Birmingham Minworth Supercentre","Birmingham","B76 1XL","England"]),
  Object.freeze(["Coventry Supercentre","Coventry","CV3 4FL","England"]),
  Object.freeze(["Leicester Supercentre","Leicester","LE3 1QN","England"]),
  Object.freeze(["Nottingham Supercentre","Nottingham","NG2 7JA","England"]),
  Object.freeze(["Derby Supercentre","Derby","DE21 7UY","England"]),
  Object.freeze(["Sheffield Supercentre","Sheffield","S13 9BN","England"]),
  Object.freeze(["Leeds Supercentre","Leeds","LS11 0BD","England"]),
  Object.freeze(["Bradford Supercentre","Bradford","BD4 7SR","England"]),
  Object.freeze(["Huddersfield Supercentre","Huddersfield","HD1 6QR","England"]),
  Object.freeze(["Manchester Eastlands Supercentre","Manchester","M11 4BD","England"]),
  Object.freeze(["Trafford Park Supercentre","Trafford","M17 8AS","England"]),
  Object.freeze(["Liverpool Iwanc","Liverpool","L15 2HF","England"]),
  Object.freeze(["St Helens Supercentre","St","WA9 1JF","England"]),
  Object.freeze(["Preston Supercentre","Preston","PR1 6QY","England"]),
  Object.freeze(["Newcastle Supercentre","Newcastle","NE6 5XN","England"]),
  Object.freeze(["Gateshead Supercentre","Gateshead","NE11 0BD","England"]),
  Object.freeze(["Sunderland Supercentre","Sunderland","SR2 7DF","England"]),
  Object.freeze(["Middlesbrough Supercentre","Middlesbrough","TS3 6AL","England"]),
  Object.freeze(["Glasgow Govan Supercentre","Glasgow","G51 3EQ","Scotland"]),
  Object.freeze(["Edinburgh Supercentre","Edinburgh","EH15 3AR","Scotland"]),
  Object.freeze(["Dundee Supercentre","Dundee","DD3 8RX","Scotland"]),
  Object.freeze(["Aberdeen Supercentre","Aberdeen","AB10 7HJ","Scotland"]),
  Object.freeze(["Belfast Shore Road Supercentre","Belfast","BT15 3PR","Northern Ireland"]),
  Object.freeze(["Newtonards Supercentre","Newtonards","BT23 4FL","Northern Ireland"]),
  Object.freeze(["Livingston Supercentre","Livingston","EH54 6NB","Scotland"]),
]);
