// [branch, city, postcode, country]
export const BM_FINAL_BRANCH_ROWS = Object.freeze([
  Object.freeze(["London Leytonstone","London","E11 1HT","England"]),
  Object.freeze(["London Beckton","London","E6 7ER","England"]),
  Object.freeze(["Manchester White City","Manchester","M16 0RP","England"]),
  Object.freeze(["Birmingham Priory","Birmingham","B4 7LL","England"]),
  Object.freeze(["Leeds Crown Point","Leeds","LS10 1ET","England"]),
  Object.freeze(["Bristol Willow Brook","Bristol","BS32 8EF","England"]),
  Object.freeze(["Glasgow Great Western","Glasgow","G15 6RX","Scotland"]),
  Object.freeze(["Edinburgh Willowbrae","Edinburgh","EH7 6LE","Scotland"]),
  Object.freeze(["Cardiff Ferry Rd","Cardiff","CF11 0JR","Wales"]),
  Object.freeze(["Belfast Retail Park","Belfast","BT12 6HT","Northern Ireland"]),
  Object.freeze(["Liverpool Edge Lane","Liverpool","L13 1AA","England"]),
  Object.freeze(["Newcastle Team Valley","Newcastle","NE11 0BD","England"]),
  Object.freeze(["Sheffield Kilner Way","Sheffield","S6 1NN","England"]),
  Object.freeze(["Nottingham Castle Retail","Nottingham","NG7 1GX","England"]),
  Object.freeze(["Leicester St Georges","Leicester","LE1 1SG","England"]),
  Object.freeze(["Coventry Airport Retail","Coventry","CV3 4RP","England"]),
  Object.freeze(["Southampton Millbrook","Southampton","SO15 0LJ","England"]),
  Object.freeze(["Portsmouth Ocean Retail","Portsmouth","PO3 5NP","England"]),
  Object.freeze(["Plymouth Coypool","Plymouth","PL7 4FB","England"]),
  Object.freeze(["Gloucester Eastern Ave","Gloucester","GL4 3EA","England"]),
  Object.freeze(["Swansea Parc Tawe","Swansea","SA1 2AL","Wales"]),
  Object.freeze(["Newport Maesglas","Newport","NP20 2NS","Wales"]),
  Object.freeze(["Wrexham Border Retail","Wrexham","LL13 8NG","Wales"]),
  Object.freeze(["Derby Ascot Drive","Derby","DE24 8GZ","England"]),
  Object.freeze(["Stockport Portwood","Stockport","SK1 2HH","England"]),
  Object.freeze(["Oldham Huddersfield Rd","Oldham","OL4 2HA","England"]),
  Object.freeze(["Bolton Burnden Retail","Bolton","BL3 2NE","England"]),
  Object.freeze(["Preston Ribble Retail","Preston","PR1 5NZ","England"]),
  Object.freeze(["Blackburn Grimshaw","Blackburn","BB2 3AG","England"]),
  Object.freeze(["Hull Clough Rd","Hull","HU5 1SR","England"]),
  Object.freeze(["Middlesbrough Cleveland","Middlesbrough","TS6 6TD","England"]),
  Object.freeze(["Sunderland Trimdon St","Sunderland","SR4 6AG","England"]),
  Object.freeze(["Dundee Kingsway","Dundee","DD3 8QF","Scotland"]),
  Object.freeze(["Aberdeen Kittybrewster","Aberdeen","AB24 4RE","Scotland"]),
  Object.freeze(["Inverness Telford St","Inverness","IV3 5LU","Scotland"]),
]);
