// [branch, city, postcode, country]
export const ENTERTAINER_FINAL_BRANCH_ROWS = Object.freeze([
  Object.freeze(["Amersham","Amersham","HP6 5AZ","England"]),
  Object.freeze(["Birmingham Bullring","Birmingham","B5 4BU","England"]),
  Object.freeze(["Bristol Cabot Circus","Bristol","BS1 3BX","England"]),
  Object.freeze(["Cardiff Queen St","Cardiff","CF10 2BY","Wales"]),
  Object.freeze(["Edinburgh Waverley Market","Edinburgh","EH1 1DE","Scotland"]),
  Object.freeze(["Leeds Trinity","Leeds","LS1 6AT","England"]),
  Object.freeze(["Leicester Highcross","Leicester","LE1 4AN","England"]),
  Object.freeze(["Liverpool ONE","Liverpool","L1 8BU","England"]),
  Object.freeze(["Manchester Arndale","Manchester","M4 3AQ","England"]),
  Object.freeze(["Newcastle Eldon Square","Newcastle","NE1 7JB","England"]),
  Object.freeze(["Nottingham Victoria Centre","Nottingham","NG1 3QN","England"]),
  Object.freeze(["Sheffield Meadowhall","Sheffield","S9 1EP","England"]),
  Object.freeze(["Southampton Westquay","Southampton","SO15 1QD","England"]),
  Object.freeze(["Brighton Churchill Square","Brighton","BN1 2RG","England"]),
  Object.freeze(["Cambridge Grand Arcade","Cambridge","CB2 3BJ","England"]),
  Object.freeze(["Coventry Lower Precinct","Coventry","CV1 1NQ","England"]),
  Object.freeze(["Derby Derbion","Derby","DE1 2PL","England"]),
  Object.freeze(["Exeter Princesshay","Exeter","EX1 1GA","England"]),
  Object.freeze(["Kingston Bentall Centre","Kingston","KT1 1TP","England"]),
  Object.freeze(["Reading Oracle","Reading","RG1 2AG","England"]),
  Object.freeze(["Plymouth Drake Circus","Plymouth","PL1 1EA","England"]),
  Object.freeze(["Oxford Westgate","Oxford","OX1 1TR","England"]),
  Object.freeze(["Bath SouthGate","Bath","BA1 1AQ","England"]),
  Object.freeze(["York Coppergate","York","YO1 9NT","England"]),
  Object.freeze(["Chester Foregate St","Chester","CH1 1HA","England"]),
  Object.freeze(["Lincoln Waterside","Lincoln","LN2 1AP","England"]),
  Object.freeze(["Norwich Chantry Place","Norwich","NR2 1SU","England"]),
  Object.freeze(["Ipswich Buttermarket","Ipswich","IP1 1DT","England"]),
  Object.freeze(["Colchester Culver Square","Colchester","CO1 1XQ","England"]),
  Object.freeze(["Chelmsford High Chelmer","Chelmsford","CM1 1XL","England"]),
  Object.freeze(["Gloucester Quays","Gloucester","GL1 5SH","England"]),
  Object.freeze(["Swansea Quadrant","Swansea","SA1 3QW","Wales"]),
  Object.freeze(["Aberdeen Union Square","Aberdeen","AB11 5RG","Scotland"]),
  Object.freeze(["Dundee Overgate","Dundee","DD1 1UF","Scotland"]),
  Object.freeze(["Belfast CastleCourt","Belfast","BT1 1DD","Northern Ireland"]),
]);
