// [branch, city, postcode, country]
export const GAME_FINAL_BRANCH_ROWS = Object.freeze([
  Object.freeze(["London Oxford St","London","W1D 1LU","England"]),
  Object.freeze(["Manchester Sports Direct","Manchester","M1 1PT","England"]),
  Object.freeze(["Birmingham New St","Birmingham","B2 4PE","England"]),
  Object.freeze(["Bristol Broadmead","Bristol","BS1 3DS","England"]),
  Object.freeze(["Leeds Briggate","Leeds","LS1 6AZ","England"]),
  Object.freeze(["Glasgow Buchanan St","Glasgow","G1 3JN","Scotland"]),
  Object.freeze(["Edinburgh Princes St","Edinburgh","EH2 2EQ","Scotland"]),
  Object.freeze(["Cardiff St David's","Cardiff","CF10 2ER","Wales"]),
  Object.freeze(["Belfast Donegall Place","Belfast","BT1 5BB","Northern Ireland"]),
  Object.freeze(["Newcastle Metrocentre","Newcastle","NE11 9YG","England"]),
  Object.freeze(["Sheffield Crystal Peaks","Sheffield","S20 7PQ","England"]),
  Object.freeze(["Nottingham Clumber St","Nottingham","NG1 3ED","England"]),
  Object.freeze(["Leicester Fosse Park","Leicester","LE19 1HX","England"]),
  Object.freeze(["Southampton Sports Direct","Southampton","SO15 1BA","England"]),
  Object.freeze(["Portsmouth Gunwharf","Portsmouth","PO1 3TZ","England"]),
  Object.freeze(["Plymouth New George St","Plymouth","PL1 1RW","England"]),
  Object.freeze(["Bournemouth Commercial Rd","Bournemouth","BH2 5NL","England"]),
  Object.freeze(["Coventry Arena Park","Coventry","CV6 6AS","England"]),
  Object.freeze(["Derby Intu","Derby","DE1 2PL","England"]),
  Object.freeze(["Stoke Hanley","Stoke","ST1 1PS","England"]),
  Object.freeze(["Wolverhampton Mander Centre","Wolverhampton","WV1 3NH","England"]),
  Object.freeze(["Hull St Stephen's","Hull","HU2 8LN","England"]),
  Object.freeze(["Middlesbrough Linthorpe Rd","Middlesbrough","TS1 1RE","England"]),
  Object.freeze(["Sunderland Bridges","Sunderland","SR1 3DR","England"]),
  Object.freeze(["Preston Fishergate","Preston","PR1 2NJ","England"]),
  Object.freeze(["Blackburn Mall","Blackburn","BB1 7JG","England"]),
  Object.freeze(["Chester Watergate St","Chester","CH1 2LA","England"]),
  Object.freeze(["Liverpool Lord St","Liverpool","L2 1TA","England"]),
  Object.freeze(["Milton Keynes Midsummer","Milton","MK9 3GB","England"]),
  Object.freeze(["Luton Mall","Luton","LU1 2TL","England"]),
]);
