// [branch, city, postcode, country]
export const TESCO_FINAL_BRANCH_ROWS = Object.freeze([
  Object.freeze(["Enfield Extra","Enfield","EN1 1TW","England"]),
  Object.freeze(["Brent Cross Extra","Brent","NW2 1LZ","England"]),
  Object.freeze(["Hatfield Extra","Hatfield","AL9 5JY","England"]),
  Object.freeze(["Watford Extra","Watford","WD17 2BD","England"]),
  Object.freeze(["Slough Extra","Slough","SL1 1XW","England"]),
  Object.freeze(["Reading Extra","Reading","RG1 8DF","England"]),
  Object.freeze(["Milton Keynes Extra","Milton","MK1 1DD","England"]),
  Object.freeze(["Colchester Extra","Colchester","CO4 9YQ","England"]),
  Object.freeze(["Ipswich Extra","Ipswich","IP5 3RU","England"]),
  Object.freeze(["Southend Extra","Southend","SS2 6XU","England"]),
  Object.freeze(["Lakeside Extra","Lakeside","RM20 3WR","England"]),
  Object.freeze(["Croydon Extra","Croydon","CR0 4RE","England"]),
  Object.freeze(["Surrey Quays Extra","Surrey","SE16 7LL","England"]),
  Object.freeze(["Yeading Extra","Yeading","UB4 0AL","England"]),
  Object.freeze(["Hayes Extra","Hayes","UB3 4FL","England"]),
  Object.freeze(["Bristol Bradley Stoke Extra","Bristol","BS32 8EF","England"]),
  Object.freeze(["Bristol Eastville Extra","Bristol","BS5 6XF","England"]),
  Object.freeze(["Coventry Extra","Coventry","CV2 2SZ","England"]),
  Object.freeze(["Birmingham Yardley Extra","Birmingham","B26 1AD","England"]),
  Object.freeze(["Dudley Extra","Dudley","DY1 4TA","England"]),
  Object.freeze(["Mansfield Extra","Mansfield","NG18 1HA","England"]),
  Object.freeze(["Nottingham Beeston Extra","Nottingham","NG9 2WJ","England"]),
  Object.freeze(["Leicester Extra","Leicester","LE4 1DE","England"]),
  Object.freeze(["Derby Extra","Derby","DE24 8EB","England"]),
  Object.freeze(["Sheffield Extra","Sheffield","S4 7UD","England"]),
  Object.freeze(["Leeds Seacroft Extra","Leeds","LS14 6JD","England"]),
  Object.freeze(["Bradford Extra","Bradford","BD6 1QN","England"]),
  Object.freeze(["Manchester Walkden Extra","Manchester","M28 3ZD","England"]),
  Object.freeze(["Oldham Extra","Oldham","OL1 1DJ","England"]),
  Object.freeze(["Stockport Extra","Stockport","SK1 2BT","England"]),
  Object.freeze(["Liverpool Woolton Extra","Liverpool","L25 7SF","England"]),
  Object.freeze(["Warrington Extra","Warrington","WA2 7NE","England"]),
  Object.freeze(["Newcastle Extra","Newcastle","NE3 2RP","England"]),
  Object.freeze(["Gateshead Extra","Gateshead","NE8 1AG","England"]),
  Object.freeze(["Sunderland Extra","Sunderland","SR6 0DA","England"]),
  Object.freeze(["Middlesbrough Extra","Middlesbrough","TS3 7AG","England"]),
  Object.freeze(["Cardiff Extra","Cardiff","CF14 3XW","Wales"]),
  Object.freeze(["Swansea Extra","Swansea","SA5 4BA","Wales"]),
  Object.freeze(["Newport Extra","Newport","NP20 2TN","Wales"]),
  Object.freeze(["Wrexham Extra","Wrexham","LL13 8HF","Wales"]),
  Object.freeze(["Glasgow Silverburn Extra","Glasgow","G53 6QR","Scotland"]),
  Object.freeze(["Edinburgh Torphin Extra","Edinburgh","EH13 0PF","Scotland"]),
  Object.freeze(["Dundee Extra","Dundee","DD2 3AP","Scotland"]),
  Object.freeze(["Aberdeen Extra","Aberdeen","AB25 3SB","Scotland"]),
  Object.freeze(["Belfast Knocknagoney Extra","Belfast","BT4 2PW","Northern Ireland"]),
]);
