import { env } from "./env.mjs";
import { ADAPTER_TYPES, RETAILER_CLASSES, RRP_AUTHORITY, VERIFICATION_STATES } from "../retailers/registry.mjs";

// Runtime scanner configuration remains backwards-compatible while carrying the
// same classification vocabulary used by the scalable UK retailer registry.
export const retailers = [
  {
    id: "pokemon-center-uk",
    name: "Pokémon Center UK",
    tcg: "pokemon",
    tcgs: ["pokemon"],
    retailerClass: RETAILER_CLASSES.NATIONAL,
    adapterType: ADAPTER_TYPES.BROWSER_COLLECTOR,
    verification: VERIFICATION_STATES.PENDING,
    rrpAuthority: RRP_AUTHORITY.OFFICIAL,
    enabled: env.retailers.pokemonCenterUk,
    baseUrl: "https://www.pokemoncenter.com/en-gb/",
    catalogueUrls: ["https://www.pokemoncenter.com/en-gb/search/tcg-cards"],
    productUrlPattern: /pokemoncenter\.com\/en-gb\/product\//i,
    skuPattern: /\/product\/([^/?#]+)/i,
    pageParam: "page",
    maxPages: 40,
    delayMs: 1800,
    officialRrpSource: true,
    include: /pokemon|tcg|trading card/i,
    exclude: null,
  },
  {
    id: "smyths-uk",
    name: "Smyths Toys UK",
    tcg: "pokemon",
    tcgs: ["pokemon"],
    retailerClass: RETAILER_CLASSES.NATIONAL,
    adapterType: ADAPTER_TYPES.GENERIC_HTML,
    verification: VERIFICATION_STATES.PENDING,
    rrpAuthority: RRP_AUTHORITY.RETAILER_REFERENCE,
    enabled: env.retailers.smythsUk,
    baseUrl: "https://www.smythstoys.com/uk/en-gb/",
    catalogueUrls: ["https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-card-game/c/SM0601011202"],
    productUrlPattern: /smythstoys\.com\/uk\/en-gb\/.*\/p\/\d+/i,
    skuPattern: /\/p\/(\d+)/i,
    pageParam: "page",
    maxPages: 4,
    delayMs: 2200,
    officialRrpSource: false,
    include: /pokemon|trading card|tcg/i,
    exclude: null,
  },
  {
    id: "chaos-cards",
    name: "Chaos Cards",
    tcg: "pokemon",
    tcgs: ["pokemon"],
    retailerClass: RETAILER_CLASSES.SPECIALIST,
    adapterType: ADAPTER_TYPES.GENERIC_HTML,
    verification: VERIFICATION_STATES.PENDING,
    rrpAuthority: RRP_AUTHORITY.RETAILER_REFERENCE,
    enabled: env.retailers.chaosCards,
    baseUrl: "https://www.chaoscards.co.uk/",
    catalogueUrls: [
      "https://www.chaoscards.co.uk/shop/card-games/pokemon/booster-boxes-pokemon",
      "https://www.chaoscards.co.uk/shop/card-games/pokemon/booster-packs-pokemon",
      "https://www.chaoscards.co.uk/shop/card-games/pokemon/collection-boxes-pokemon",
      "https://www.chaoscards.co.uk/shop/card-games/pokemon/elite-trainer-boxes-pokemon",
      "https://www.chaoscards.co.uk/shop/card-games/pokemon/gift-tins-pokemon",
      "https://www.chaoscards.co.uk/shop/card-games/pokemon/japanese-products-pokemon",
      "https://www.chaoscards.co.uk/shop/card-games/pokemon/other-sealed-products-pokemon",
      "https://www.chaoscards.co.uk/shop/card-games/pokemon/theme-decks-pokemon"
    ],
    productUrlPattern: /chaoscards\.co\.uk\/prod\//i,
    skuPattern: /\/prod\/[^/]+\/([^/?#]+)$/i,
    pageParam: "page",
    maxPages: 20,
    delayMs: 1800,
    officialRrpSource: false,
    include: /pokemon/i,
    exclude: /\bsingle\b|code card|online play/i,
  },
].filter((retailer) => retailer.enabled);
