import { env } from "./env.mjs";
import { ADAPTER_TYPES, RETAILER_CLASSES, RRP_AUTHORITY, VERIFICATION_STATES } from "../retailers/registry.mjs";

const SEALED_POKEMON = /pokemon|pokémon/i;
const SEALED_PRODUCT = /booster|elite trainer|\betb\b|collection|tin\b|blister|deck\b|battle academy|trainer toolkit|build\s*&\s*battle|premium|bundle|display|box\b|pack\b|poster|tech sticker|mini portfolio|first partner|ultra premium/i;
const NON_PRODUCT = /\bsingle\b|code card|sleeve|binder only|playmat|toploader|graded|\bpsa\b|\bcgc\b|\bbgs\b/i;

function shopifyPokemonRetailer({ id, name, enabled, baseUrl, collection, retailerClass = RETAILER_CLASSES.INDEPENDENT, maxPages = 20, delayMs = 900, include = SEALED_PRODUCT, exclude = NON_PRODUCT }) {
  return {
    id,
    name,
    tcg: "pokemon",
    tcgs: ["pokemon"],
    retailerClass,
    adapterType: ADAPTER_TYPES.SHOPIFY,
    verification: VERIFICATION_STATES.PENDING,
    rrpAuthority: RRP_AUTHORITY.RETAILER_REFERENCE,
    enabled,
    baseUrl,
    catalogue: {
      feedUrl: new URL(`${collection.replace(/\/$/, "")}/products.json?limit=250`, baseUrl).toString(),
      feedApproved: true,
      runtime: { maxPages, delayMs },
    },
    officialRrpSource: false,
    include,
    exclude,
  };
}

export const retailers = [
  {
    id: "pokemon-center-uk",
    name: "Pokémon Center UK",
    tcg: "pokemon",
    tcgs: ["pokemon"],
    retailerClass: RETAILER_CLASSES.NATIONAL,
    adapterType: ADAPTER_TYPES.BROWSER_COLLECTOR,
    verification: VERIFICATION_STATES.PENDING,
    rrpAuthority: RRP_AUTHORITY.OFFICIAL,
    enabled: env.retailers.pokemonCenterUk,
    baseUrl: "https://www.pokemoncenter.com/en-gb/",
    catalogueUrls: ["https://www.pokemoncenter.com/en-gb/search/tcg-cards"],
    productUrlPattern: /pokemoncenter\.com\/en-gb\/product\//i,
    skuPattern: /\/product\/([^/?#]+)/i,
    pageParam: "page",
    maxPages: 40,
    delayMs: 1800,
    officialRrpSource: true,
    include: /pokemon|tcg|trading card/i,
    exclude: null,
  },
  {
    id: "smyths-uk",
    name: "Smyths Toys UK",
    tcg: "pokemon",
    tcgs: ["pokemon"],
    retailerClass: RETAILER_CLASSES.NATIONAL,
    adapterType: ADAPTER_TYPES.GENERIC_HTML,
    verification: VERIFICATION_STATES.PENDING,
    rrpAuthority: RRP_AUTHORITY.RETAILER_REFERENCE,
    enabled: env.retailers.smythsUk,
    baseUrl: "https://www.smythstoys.com/uk/en-gb/",
    catalogueUrls: ["https://www.smythstoys.com/uk/en-gb/toys/action-figures-and-playsets/pokemon/pokemon-trading-card-game/c/SM0601011202"],
    productUrlPattern: /smythstoys\.com\/uk\/en-gb\/.*\/p\/\d+/i,
    skuPattern: /\/p\/(\d+)/i,
    pageParam: "page",
    maxPages: 4,
    delayMs: 2200,
    officialRrpSource: false,
    include: /pokemon|trading card|tcg/i,
    exclude: null,
  },
  {
    id: "chaos-cards",
    name: "Chaos Cards",
    tcg: "pokemon",
    tcgs: ["pokemon"],
    retailerClass: RETAILER_CLASSES.SPECIALIST,
    adapterType: ADAPTER_TYPES.GENERIC_HTML,
    verification: VERIFICATION_STATES.PENDING,
    rrpAuthority: RRP_AUTHORITY.RETAILER_REFERENCE,
    enabled: env.retailers.chaosCards,
    baseUrl: "https://www.chaoscards.co.uk/",
    catalogueUrls: [
      "https://www.chaoscards.co.uk/shop/card-games/pokemon/booster-boxes-pokemon",
      "https://www.chaoscards.co.uk/shop/card-games/pokemon/booster-packs-pokemon",
      "https://www.chaoscards.co.uk/shop/card-games/pokemon/collection-boxes-pokemon",
      "https://www.chaoscards.co.uk/shop/card-games/pokemon/elite-trainer-boxes-pokemon",
      "https://www.chaoscards.co.uk/shop/card-games/pokemon/gift-tins-pokemon",
      "https://www.chaoscards.co.uk/shop/card-games/pokemon/japanese-products-pokemon",
      "https://www.chaoscards.co.uk/shop/card-games/pokemon/other-sealed-products-pokemon",
      "https://www.chaoscards.co.uk/shop/card-games/pokemon/theme-decks-pokemon"
    ],
    productUrlPattern: /chaoscards\.co\.uk\/prod\//i,
    skuPattern: /\/prod\/[^/]+\/([^/?#]+)$/i,
    pageParam: "page",
    maxPages: 20,
    delayMs: 1800,
    officialRrpSource: false,
    include: /pokemon/i,
    exclude: /\bsingle\b|code card|online play/i,
  },
  {
    id: "hamleys-uk",
    name: "Hamleys UK",
    tcg: "pokemon",
    tcgs: ["pokemon"],
    retailerClass: RETAILER_CLASSES.NATIONAL,
    adapterType: ADAPTER_TYPES.GENERIC_HTML,
    verification: VERIFICATION_STATES.PENDING,
    rrpAuthority: RRP_AUTHORITY.RETAILER_REFERENCE,
    enabled: env.retailers.hamleysUk,
    baseUrl: "https://www.hamleys.com/",
    catalogueUrls: ["https://www.hamleys.com/by-brand/pokemon"],
    productUrlPattern: /hamleys\.com\/(?!by-brand\/|category\/|search\/|customer\/|checkout\/)[a-z0-9][a-z0-9-]+\/?(?:\?.*)?$/i,
    skuPattern: /\/([^/?#]+)\/?(?:\?|$)/i,
    pageParam: "p",
    maxPages: 8,
    delayMs: 1800,
    officialRrpSource: false,
    include: /pokemon.*(?:tcg|trading card|booster|elite trainer|collection|tin|deck)|(?:tcg|trading card).*pokemon/i,
    exclude: /plush|figure|puzzle|colouring|stationery|lego|nanoblock/i,
  },
  {
    id: "asda-uk",
    name: "ASDA",
    tcg: "pokemon",
    tcgs: ["pokemon"],
    retailerClass: RETAILER_CLASSES.NATIONAL,
    adapterType: ADAPTER_TYPES.GENERIC_HTML,
    verification: VERIFICATION_STATES.PENDING,
    rrpAuthority: RRP_AUTHORITY.RETAILER_REFERENCE,
    enabled: env.retailers.asdaUk,
    baseUrl: "https://www.asda.com/",
    catalogueUrls: ["https://www.asda.com/groceries/search/pokemon%20tcg"],
    productUrlPattern: /asda\.com\/groceries\/product\/[^/]+\/[^/]+\/\d+/i,
    skuPattern: /\/(\d+)(?:\?|$)/i,
    pageParam: "page",
    maxPages: 6,
    delayMs: 2200,
    officialRrpSource: false,
    include: /pokemon.*(?:tcg|trading card|booster|collection|tin|deck|blister|box)|(?:tcg|trading card).*pokemon/i,
    exclude: null,
  },
  {
    id: "tesco-uk",
    name: "Tesco",
    tcg: "pokemon",
    tcgs: ["pokemon"],
    retailerClass: RETAILER_CLASSES.NATIONAL,
    adapterType: ADAPTER_TYPES.GENERIC_HTML,
    verification: VERIFICATION_STATES.PENDING,
    rrpAuthority: RRP_AUTHORITY.RETAILER_REFERENCE,
    enabled: env.retailers.tescoUk,
    baseUrl: "https://www.tesco.com/",
    catalogueUrls: ["https://www.tesco.com/shop/en-GB/browse/toys-and-games/collectible-figures/trading-cards-and-accessories/trading-cards-and-accessories"],
    productUrlPattern: /tesco\.com\/(?:shop|groceries)\/en-GB\/products\/\d+/i,
    skuPattern: /\/products\/(\d+)/i,
    pageParam: "page",
    maxPages: 15,
    delayMs: 2200,
    officialRrpSource: false,
    include: /pokemon.*(?:tcg|trading card|booster|collection|tin|deck|blister|box)|(?:tcg|trading card).*pokemon/i,
    exclude: /marketplace|sold by marketplace seller|korean|tcym/i,
  },
  {
    id: "entertainer-uk",
    name: "The Entertainer",
    tcg: "pokemon",
    tcgs: ["pokemon"],
    retailerClass: RETAILER_CLASSES.NATIONAL,
    adapterType: ADAPTER_TYPES.GENERIC_HTML,
    verification: VERIFICATION_STATES.PENDING,
    rrpAuthority: RRP_AUTHORITY.RETAILER_REFERENCE,
    enabled: env.retailers.entertainerUk,
    baseUrl: "https://www.thetoyshop.com/",
    catalogueUrls: ["https://www.thetoyshop.com/c/pocket-money/trading-cards?page=1"],
    productUrlPattern: /thetoyshop\.com\/[^?#]*\/p\/[^/?#]+/i,
    skuPattern: /\/p\/([^/?#]+)/i,
    pageParam: "page",
    maxPages: 8,
    delayMs: 2200,
    officialRrpSource: false,
    include: /pokemon.*(?:tcg|trading card|booster|collection|tin|deck|blister|box)|(?:tcg|trading card).*pokemon/i,
    exclude: null,
  },
  {
    id: "game-uk",
    name: "GAME UK",
    tcg: "pokemon",
    tcgs: ["pokemon"],
    retailerClass: RETAILER_CLASSES.NATIONAL,
    adapterType: ADAPTER_TYPES.GENERIC_HTML,
    verification: VERIFICATION_STATES.PENDING,
    rrpAuthority: RRP_AUTHORITY.RETAILER_REFERENCE,
    enabled: env.retailers.gameUk,
    baseUrl: "https://www.game.co.uk/",
    catalogueUrls: ["https://www.game.co.uk/toys/trading-cards", "https://www.game.co.uk/toys/trading-cards/booster-packs"],
    productUrlPattern: /game\.co\.uk\/[a-z0-9][a-z0-9-]+-\d{6}(?:\?.*)?$/i,
    skuPattern: /-(\d{6})(?:\?|$)/i,
    pageParam: "dcp",
    maxPages: 8,
    delayMs: 2200,
    officialRrpSource: false,
    include: /pokemon/i,
    exclude: /playmat|deck box|sleeve|binder|accessor/i,
  },
  {
    id: "argos-uk",
    name: "Argos",
    tcg: "pokemon",
    tcgs: ["pokemon"],
    retailerClass: RETAILER_CLASSES.NATIONAL,
    adapterType: ADAPTER_TYPES.GENERIC_HTML,
    verification: VERIFICATION_STATES.PENDING,
    rrpAuthority: RRP_AUTHORITY.RETAILER_REFERENCE,
    enabled: env.retailers.argosUk,
    baseUrl: "https://www.argos.co.uk/",
    catalogueUrls: ["https://www.argos.co.uk/sd/pokemon-tcg/"],
    productUrlPattern: /argos\.co\.uk\/product\/\d+/i,
    skuPattern: /\/product\/(\d+)/i,
    pageParam: "page",
    maxPages: 8,
    delayMs: 2200,
    officialRrpSource: false,
    include: /pokemon.*(?:tcg|trading card|booster|elite trainer|collection|tin|deck|blister|display box|battle academy)/i,
    exclude: /nintendo switch|jigsaw|colouring|figure|bedding|stationery|lego|monopoly/i,
  },
  {
    id: "magic-madhouse",
    name: "Magic Madhouse",
    tcg: "pokemon",
    tcgs: ["pokemon"],
    retailerClass: RETAILER_CLASSES.SPECIALIST,
    adapterType: ADAPTER_TYPES.GENERIC_HTML,
    verification: VERIFICATION_STATES.PENDING,
    rrpAuthority: RRP_AUTHORITY.RETAILER_REFERENCE,
    enabled: env.retailers.magicMadhouse,
    baseUrl: "https://magicmadhouse.co.uk/",
    catalogueUrls: ["https://magicmadhouse.co.uk/pokemon/pokemon-sealed-product"],
    catalogue: {
      sitemapUrl: "https://magicmadhouse.co.uk/xmlsitemap.php",
      runtime: {
        maxProductPages: 800,
        productConcurrency: 4,
        productBatchDelayMs: 500,
      },
    },
    productUrlPattern: /magicmadhouse\.co\.uk\/pokemon-[a-z0-9][a-z0-9-]+\/?(?:\?.*)?$/i,
    skuPattern: /\/pokemon-([^/?#]+)/i,
    pageParam: "page",
    maxPages: 20,
    delayMs: 2200,
    officialRrpSource: false,
    include: SEALED_POKEMON,
    exclude: NON_PRODUCT,
  },
  shopifyPokemonRetailer({ id: "double-sleeved", name: "Double Sleeved", enabled: env.retailers.doubleSleeved, baseUrl: "https://www.doublesleeved.co.uk/", collection: "/collections/pokemon-tcg", maxPages: 6 }),
  shopifyPokemonRetailer({ id: "total-cards", name: "Total Cards", enabled: env.retailers.totalCards, baseUrl: "https://totalcards.net/", collection: "/collections/pokemon-sealed-products", retailerClass: RETAILER_CLASSES.SPECIALIST, maxPages: 12, include: SEALED_POKEMON }),
  shopifyPokemonRetailer({ id: "titan-cards", name: "Titan Cards", enabled: env.retailers.titanCards, baseUrl: "https://titancards.co.uk/", collection: "/collections/pokemon-sealed-products", maxPages: 6, include: SEALED_POKEMON }),
  shopifyPokemonRetailer({ id: "eterna-cards", name: "Eterna Cards", enabled: env.retailers.eternaCards, baseUrl: "https://eternacards.co.uk/", collection: "/collections/pokemon-tcg-sealed-products", maxPages: 8, include: SEALED_POKEMON }),
  shopifyPokemonRetailer({ id: "card-collective", name: "Card Collective UK", enabled: env.retailers.cardCollective, baseUrl: "https://card-collective.com/", collection: "/collections/pokemon-tcg", maxPages: 6 }),
  shopifyPokemonRetailer({ id: "jet-cards", name: "JET Cards", enabled: env.retailers.jetCards, baseUrl: "https://jetcards.uk/", collection: "/collections/pokemon-trading-cards", maxPages: 6 }),
  shopifyPokemonRetailer({ id: "gathering-games", name: "Gathering Games", enabled: env.retailers.gatheringGames, baseUrl: "https://gatheringgames.co.uk/", collection: "/collections/pokemon", maxPages: 6 }),
  shopifyPokemonRetailer({ id: "zatu-games", name: "Zatu Games", enabled: env.retailers.zatuGames, baseUrl: "https://zatu.com/", collection: "/collections/other-sealed-product-pokemon", retailerClass: RETAILER_CLASSES.SPECIALIST, maxPages: 4, delayMs: 2500, include: SEALED_POKEMON }),
].filter((retailer) => retailer.enabled);
